// <auto-generated />
namespace SISPTD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Removidodatenulldoagendamento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removidodatenulldoagendamento));
        
        string IMigrationMetadata.Id
        {
            get { return "201605162028053_Removido date null do agendamento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
