// <auto-generated />
namespace SISPTD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class excluircamppaciente_PessoaIddatbrequisicao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(excluircamppaciente_PessoaIddatbrequisicao));
        
        string IMigrationMetadata.Id
        {
            get { return "201605142029100_excluir camp paciente_PessoaId da tb requisicao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
