// <auto-generated />
namespace SISPTD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Alteracaoctabdomeiocomtipo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alteracaoctabdomeiocomtipo));
        
        string IMigrationMetadata.Id
        {
            get { return "201605142011021_Alteracao c tab do meio com tipo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
