// <auto-generated />
namespace SISPTD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class relacaopessoa_requisicao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relacaopessoa_requisicao));
        
        string IMigrationMetadata.Id
        {
            get { return "201604170025024_relacao pessoa_requisicao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
