// <auto-generated />
namespace SISPTD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Altrelacaopessoarequisica : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Altrelacaopessoarequisica));
        
        string IMigrationMetadata.Id
        {
            get { return "201605150456282_Alt relacao pessoa requisica"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
