// <auto-generated />
namespace Sptd.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlterTamCampoNometbPessoa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterTamCampoNometbPessoa));
        
        string IMigrationMetadata.Id
        {
            get { return "201602231516274_AlterTamCampoNometbPessoa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
